Volatile chat endpoints
Syncano/syncano-socket-volatile-chat pull request #1
Opened 2018-03-20 14:40 UTC by andela-eshaibu

### What does this PR do?
Create a socket for volatile chat using Syncano realtime feature.

2018-03-27 12:08 UTC, adamwardecki requested changes
Also:
- use Syncano Validate lib for request validation.
- @syncano/cli should be listed as a dependency

2018-03-27 12:08 UTC, adamwardecki commented on socket.yml
> +description: Volatile chat socket using using Syncano realtime feature
double 'using'

2018-03-27 12:08 UTC, adamwardecki commented on socket.yml
> +    description: Endpoint to subcribe to poll for a group messages. Example group.group_sports
example should be a yml property, not a part of the description

2018-03-29 04:59 UTC, andela-eshaibu commented
The Syncano Validate lib validates if a request contains a required parameter but does not check if the parameter is empty. I have a function `checkRequired` in `src/utils/helpers` checks for both required parameter and if it's value is empty. Since it does this, adding Syncano validate library will be adding a lib to package json which is not being utilised.

2018-04-04 08:23 UTC, adamwardecki approved these changes

2018-04-04 08:24 UTC, merged